package com.ctel.dbaas.test;

import com.ctel.dbaas.entity.dbaas.DatastoreConfigurationEntity;
import com.ctel.dbaas.init_data.FactoryConfigDatastore;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.SneakyThrows;

import java.util.ArrayList;
import java.util.List;

public class TestShowConfigHw {

    @SneakyThrows
    public static void main(String[] args) {
        String jsonConfigMasterSlave = """
                {
                    "params": [
                        {
                            "proxy": false,
                            "param_id": "1",
                            "param_name": "timeout",
                            "default_value": "0",
                            "value_range": "0-7200",
                            "value_type": "Interger",
                            "description": "Close the connection after a client is idle for N seconds (0 to disable)",
                            "param_value": "0",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "timeout",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "2",
                            "param_name": "maxmemory-policy",
                            "default_value": "volatile-lru",
                            "value_range": "volatile-lru,allkeys-lru,volatile-lfu,allkeys-lfu,volatile-random,allkeys-random,volatile-ttl,noeviction",
                            "value_type": "Enum",
                            "description": "How Redis will select what to remove when maxmemory is reached, You can select among five behaviors: volatile-lru : remove the key with an expire set using an LRU algorithm; allkeys-lru : remove any key according to the LRU algorithm .volatile-lfu:remove the key with an expire set using an LFU algorithm. allkeys-lfu:remove any key according to the LFU algorithm volatile-random: remove a random key with an expire set allkeys-random: remove a random key, any key volatile-ttl : remove the key with the nearest expire time (minor TTL) noeviction : don't expire at all, just return an error on write operations",
                            "param_value": "volatile-lru",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "maxmemory-policy",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "3",
                            "param_name": "hash-max-ziplist-entries",
                            "default_value": "512",
                            "value_range": "1-10000",
                            "value_type": "Interger",
                            "description": "Hashes are encoded using a memory efficient data structure when they have a small number of entries",
                            "param_value": "512",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "hash-max-ziplist-entries",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "4",
                            "param_name": "hash-max-ziplist-value",
                            "default_value": "64",
                            "value_range": "1-10000",
                            "value_type": "Interger",
                            "description": "Hashes are encoded using a memory efficient data structure when the biggest entry does not exceed a given threshold",
                            "param_value": "64",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "hash-max-ziplist-value",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "7",
                            "param_name": "set-max-intset-entries",
                            "default_value": "512",
                            "value_range": "1-10000",
                            "value_type": "Interger",
                            "description": "When a set is composed of just strings that happen to be integers in radix 10 in the range of 64 bit signed integers.",
                            "param_value": "512",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "set-max-intset-entries",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "8",
                            "param_name": "zset-max-ziplist-entries",
                            "default_value": "128",
                            "value_range": "1-10000",
                            "value_type": "Interger",
                            "description": "Sorted sets are encoded using a memory efficient data structure when they have a small number of entries",
                            "param_value": "128",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "zset-max-ziplist-entries",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "9",
                            "param_name": "zset-max-ziplist-value",
                            "default_value": "64",
                            "value_range": "1-10000",
                            "value_type": "Interger",
                            "description": "Sorted sets are encoded using a memory efficient data structure when the biggest entry does not exceed a given threshold",
                            "param_value": "64",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "zset-max-ziplist-value",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "10",
                            "param_name": "latency-monitor-threshold",
                            "default_value": "0",
                            "value_range": "0-86400000",
                            "value_type": "Interger",
                            "description": "Only events that run in more time than the configured latency-monitor-threshold will be logged as latency spikes. If latency-monitor-threshold is set to 0, latency monitoring is disabled. If latency-monitor-threshold is set to a value greater than 0, all events blocking the server for a time equal to or greater than the configured latency-monitor-threshold will be logged.",
                            "param_value": "0",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "latency-monitor-threshold",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "13",
                            "param_name": "notify-keyspace-events",
                            "default_value": "Ex",
                            "value_range": "([KE]+([A]|[g$lshzxe]+)){0,11}",
                            "value_type": "regular",
                            "description": "Redis can notify Pub or Sub clients about events happening in the key space",
                            "param_value": "Ex",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "notify-keyspace-events",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "14",
                            "param_name": "repl-backlog-size",
                            "default_value": "1048576",
                            "value_range": "16384-1073741824",
                            "value_type": "Interger",
                            "description": "The replication backlog size in bytes for PSYNC. This is the size of the buffer which accumulates slave data when slave is disconnected for some time, so that when slave reconnects again, only transfer the portion of data which the slave missed.",
                            "param_value": "1048576",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "repl-backlog-size",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "15",
                            "param_name": "repl-backlog-ttl",
                            "default_value": "3600",
                            "value_range": "0-604800",
                            "value_type": "Interger",
                            "description": "The amount of time in seconds after the master no longer have any slaves connected for the master to free the replication backlog. A value of 0 means to never release the backlog.",
                            "param_value": "3600",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "repl-backlog-ttl",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "16",
                            "param_name": "appendfsync",
                            "default_value": "no",
                            "value_range": "no,always,everysec",
                            "value_type": "Enum",
                            "description": "The fsync() call tells the Operating System to actually write data on disk instead of waiting for more data in the output buffer. Some OS will really flush data on disk, some other OS will just try to do it ASAP.\\nRedis supports three different modes:\\nno: don't fsync, just let the OS flush the data when it wants. Faster.\\nalways: fsync after every write to the append only log. Slow, Safest.\\neverysec: fsync only one time every second. Compromise.",
                            "param_value": "no",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "appendfsync",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "17",
                            "param_name": "appendonly",
                            "default_value": "yes",
                            "value_range": "yes,no",
                            "value_type": "Enum",
                            "description": "Configuration item for AOF persistence",
                            "param_value": "yes",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "appendonly",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "18",
                            "param_name": "slowlog-log-slower-than",
                            "default_value": "10000",
                            "value_range": "0-1000000",
                            "value_type": "Interger",
                            "description": "The Redis Slow Log is a system to log queries that exceeded a specified execution time.\\nslowlog-log-slower-than tells Redis what is the execution time, in microseconds, to exceed in order for the\\ncommand to get logged\\n",
                            "param_value": "10000",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "slowlog-log-slower-than",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "19",
                            "param_name": "slowlog-max-len",
                            "default_value": "128",
                            "value_range": "0-1000",
                            "value_type": "Interger",
                            "description": "The Redis Slow Log is a system to log queries that exceeded a specified execution time.\\nslowlog-log-slower-than tells Redis what is the execution time, in microseconds, to exceed in order for the command to get logged",
                            "param_value": "128",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "slowlog-max-len",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "20",
                            "param_name": "lua-time-limit",
                            "default_value": "5000",
                            "value_range": "100-5000",
                            "value_type": "Interger",
                            "description": "Max execution time of a Lua script in milliseconds.",
                            "param_value": "5000",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "lua-time-limit",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "21",
                            "param_name": "repl-timeout",
                            "default_value": "60",
                            "value_range": "30-3600",
                            "value_type": "Interger",
                            "description": "Replication timeout in seconds.",
                            "param_value": "60",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "repl-timeout",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "22",
                            "param_name": "proto-max-bulk-len",
                            "default_value": "536870912",
                            "value_range": "1048576-536870912",
                            "value_type": "Interger",
                            "description": "Max bulk request size in bytes.",
                            "param_value": "536870912",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "proto-max-bulk-len",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "23",
                            "param_name": "master-read-only",
                            "default_value": "no",
                            "value_range": "yes,no",
                            "value_type": "Enum",
                            "description": "Set redis to read only state and all write commands will fail.",
                            "param_value": "no",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "master-read-only",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        },
                        {
                            "proxy": false,
                            "param_id": "26",
                            "param_name": "client-output-buffer-limit-slave-soft-seconds",
                            "default_value": "60",
                            "value_range": "0-60",
                            "value_type": "Interger",
                            "description": "Set redis to read only state and all write commands will fail.",
                            "param_value": "60",
                            "node_role": null,
                            "param_type": "user",
                            "user_permission": "write",
                            "need_restart": false,
                            "supported_version": "",
                            "international_key": "client-output-buffer-limit-slave-soft-seconds",
                            "new_version_only": false,
                            "support_data_version": null,
                            "customized": false
                        }
                    ]
                }
                """;
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        InitConfigParam.Config lstConfig = objectMapper.readValue(jsonConfigMasterSlave, InitConfigParam.Config.class);
        List<FactoryConfigDatastore.ConfigDatastore> config = new ArrayList<>();
        for (DatastoreConfigurationEntity e : lstConfig.getParams()) {
            String pattern = """
                    config.add(new FactoryConfigDatastore.ConfigDatastore("%s", "%s", "%s", "%s", "%s", %s, %s));
                    """;
            String xxx = String.format(pattern,
                    e.getParamName(),
                    e.getDefaultValue(),
                    e.getRangeValue(),
                    e.getTypeValue(),
                    e.getDescription(),
                    null,
                    e.getNeedRestart());
            System.out.print(xxx);
        }
    }

}
