server.port=8085
server.tomcat.max-threads=8
spring.datasource.tomcat.testWhileIdle=true
spring.datasource.tomcat.timeBetweenEvictionRunsMillis=60000
spring.datasource.tomcat.validationQuery=SELECT 1
logging.level.n.jworkflow.kernel.services.PollThread=OFF